spring:
  application:
    name: event-ingestion-service
  datasource:
    url: jdbc:postgresql://localhost:5432/jumarkot
    username: jumarkot
    password: jumarkot
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
